#Kehitysympäristön asetukset (käytää H2-tietokantaa)
#Yleiset asetukset application.properties -tiedostossa, vain tietokanta-asetukset erikseen tässä dev-tiedostossa

# Yhteysasetukset 
#Väliaikaisen kehityskannan (H2-tietokanta) asetukset (käytä vain kehityksessä, ei tuotannossa)
# H2-konsoli selaimessa osoitteessa /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# In-memory tietokanta
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Luodaan taulut alusta joka käynnistyksessä (tyhjentää datan)
spring.jpa.hibernate.ddl-auto=create-drop