#Tuotantoympäristön asetukset (käytää PostgreSQL-tietokantaa)
#Yleiset asetukset application.properties -tiedostossa, vain tietokanta-asetukset erikseen tässä prod-tiedostossa

# Yhteysasetukset - hakee tiedot ympäristöstä
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

server.port=${PORT:8080}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 'update' säilyttää datan ja päivittää vain muutokset tauluihin
spring.jpa.hibernate.ddl-auto=update